/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.testapp;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int _tex1=0x7f020000;
        public static final int tex1=0x7f020001;
    }
    public static final class string {
        public static final int hello=0x7f030000;
    }
}
